### ISSUE TITLE
Most of the time we are facing OutOfMemory Exception! Any solutions?

### ISSUE THREAD

**Issue by asifjavaid** [hkk595/Resizer#5]
java.lang.OutOfMemoryError: Failed to allocate a 63489036 byte allocation with 16776592 free bytes and 58MB until OOM
        at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
        at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
        at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:882)
        at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:858)
        at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:478)
        at me.echodev.resizer.util.ImageUtils.getScaledBitmap(ImageUtils.java:34)
        at me.echodev.resizer.util.ImageUtils.getScaledImage(ImageUtils.java:25)
        at me.echodev.resizer.Resizer.getResizedFile(Resizer.java:149)

Please suggest!

**Comment by jifferon** [comment]
60 mb of file seems like a huge deal, does not it? Maybe for your case you need something more advanced and low-leveled

**Comment by Duna** [comment]
All 2019+ samsung phones have photosize set to 64MP, it should work
